notaryproject/notaryproject.dev

- .github/settings.yml
Setting repo defaults, labels
Adding @caniszczyk as admin, @nate-double-u as maintainer
> Adding .github/settings.yml

- .github/settings.yml
Fixes #3 
Adding new admin & maintenance users.
> Adding new maintainers to .github/settings.yml

- .github/settings.yml
Adding labels to the repo:
- infrastructure
- ux
- design
- upstream
- blocked
- dependencies
> Update .github/settings.yml with new labels

- .htmltest.external.yml
- .htmltest.yml
- Makefile
- README.md
- package.json
- Prep work for #37
- Add support for external link checking
- Don't fetch the link checker if we have it already
> Add external link checking, and other improvements

- package.json
- `serve` script: drop unnecessary flag
- Refresh of submodule scripts
> NPM script updates

- .gitpod.yml
Looking at gitpod.io as a development environment. Adding `.gitpod.yml` file for setup.
Signed-off-by: Nate W <4453979+nate-double-u@users.noreply.github.com>
> Setting up Gitpod.io .gitpod.yml file

- content/en/docs/_index.md
- content/en/docs/notation-go/_index.md
- content/en/docs/notation/_index.md
- content/en/docs/tuf/_index.md
fixes #55 
Deploy previews:
* https://deploy-preview-56--notarydev.netlify.app/docs/
* https://deploy-preview-56--notarydev.netlify.app/docs/notation/
* https://deploy-preview-56--notarydev.netlify.app/docs/notation-go/
* https://deploy-preview-56--notarydev.netlify.app/docs/tuf/
> Updating project descriptions & showing them on the docs landing page

- README.md
Signed-off-by: Patrice Chalin <chalin@users.noreply.github.com>
> README: drop mention of ancestry (etcd.io)

- config.yaml
- content/en/blog/_index.md
- content/en/docs/_index.md
Signed-off-by: reddymahendra52 reddymahendra52@gmail.com
I have also tried to resolve issue #61 by implementing the potential solutions mentioned in the respective issue.
> Moved menu items from config.yaml to respective folders so that they are shown as active when section pages are being viewed

- content/en/docs/installation/cli.md
Signed-off-by: Zach Rhoads <zachary.rhoads@microsoft.com>
fixes #83
Updates to CLI install instructions for platforms
> Updates install CLI doc with more detail

- content/en/docs/quickstart.md
Signed-off-by: Zach Rhoads <zachary.rhoads@microsoft.com>
Added a note about an extra parameter needed for apple silicon when starting the registry
> add callout for apple silicon for oras registry

- content/en/docs/tutorials/trust-policy.md
Signed-off-by: Zach Rhoads <zachary.rhoads@microsoft.com>
fixes #98
> add tutorial for trust policy

- .htmltest.yml
- Makefile
- Closes #37
/cc @thisisobate @nate-double-u
> Makefile: cleanup link checking

- content/en/docs/how-to/notation-config-file.md
- content/en/docs/installation/cli.md
* Adds example of remote key in signingkeys.json
* Reworded verify notation checksum section
* Also, fixed some linting errors
> doc: adds example of remote key in signingkeys.json & Rewords verify notation checksum section

- content/en/blog/2023/announcing-notation-rc3.md
Update:
- Add a blog for notation v1.0.0-rc.3 release
> doc: create blog for notation v1.0.0-rc.3 release

- content/en/docs/installation/cli.md
- content/en/docs/installation/uninstall.md
- content/en/docs/quickstart.md
> added uninstall instructions

- content/en/docs/how-to/registry-authentication.md
> add how-to for authenticating with registries

- content/en/docs/faq.md
Added FAQ entry with the list of compatible registries
Fixes #104
> add FAQ entry for compatable registries

- layouts/partials/banner.html
Proposed changes to banner to add clarity around state of notation cli and docs
> updated banner to add caveat about RC state

- README.md
> added clarifying statements to README, directing people to the docs

- CONTRIBUTING.md
- content/en/docs/concepts/directory-structure.md
- content/en/docs/how-to/notation-config-file.md
- content/en/docs/how-to/registry-authentication.md
- content/en/docs/installation/cli.md
- content/en/docs/installation/uninstall.md
- content/en/docs/overview.md
- content/en/docs/quickstart.md
- content/en/docs/tutorials/trust-policy.md
Update notice block for better view in Hugo.
> doc: update notice

- config.yaml
> chore: fix website page title to always contain value

- content/en/docs/troubleshooting.md
Add troubleshooting entries for inspecting artifact descriptors.
fixes #120
> Add troubleshooting entry for inspecting artifact descriptors

- content/en/docs/how-to/manage-trust-policy.md
> added manage trust policies doc

- content/en/docs/how-to/oci-image-layout.md
> add how-to for OCI image layout

- content/en/docs/troubleshooting.md
> add entries to troubleshooting

- content/en/docs/quickstart.md
> added note fixing #221

- content/en/docs/how-to/registry-authentication.md
> added callout about insecure use of env var

- content/en/docs/concepts/experimental-features.md
> add experimental features concepts doc

- content/en/blog/2023/announcing-notation-rc5.md
> doc: add Notation v1.0.0-RC.5 release blog

- content/en/docs/installation/cli.md
- layouts/partials/banner.html
update install and banner for RC.7
> doc: update install and banner for RC.7

- content/en/blog/2023/announcing-notation-rc6.md
Update:
- create a blog for Notation v1.0.0-RC.7 release
> doc: release blog for Notation RC-7

- content/en/blog/2023/announcing-notation-rc6.md
> doc: add CVE IDs for rc.7 blog

- content/en/docs/how-to/delete-signature.md
> added steps for deleting a signature

- content/en/docs/quickstart.md
This PR fixed #283 
I have updated the docker inspect command in the quickstart guide to rightly inspect the sample image.
> Updated quickstart.md file

- content/en/docs/how-to/registry-authentication.md
> Update registry authentication with cred store

- content/en/security-audit/audit-2023-1.md
- content/en/security-audit/audit-2023-2.md
To add a new link in the security audit, created a new `.md` file.
#307 
https://deploy-preview-308--notarydev.netlify.app/security-audit/
> Notary fuzzing audit link fixed

- content/en/docs/faq.md
fixes: #232
The FAQ page markdown file had styling issues regarding the boldness of the text. This PR fixes them.
Screenshots of the fix:
Before:
After:
> Docs: Fix FAQ font style

- content/en/docs/overview.md
> corrected spelling mistake in overview.md

- content/en/docs/quickstart.md
> docs: update quickstart.md

- content/en/docs/_index.md
- content/en/docs/overview.md
> doc: overhaul overview

- content/en/docs/installation/cli.md
This PR fixes the second item on issue #324
> Added homebrew and winget installation binaries to the installation guide

- content/en/docs/user-guides/how-to/plugin-management.md
Adding support for Venafi CodeSign Protect plugin for notation.
> venafi plugin support

- content/en/blog/2023/notary-enlightning-podcast.md
> added blog post linking to appearance on the enlightning podcast

- content/en/docs/quickstart-guides/quickstart-sign-image-artifact.md
- content/en/docs/quickstart-guides/quickstart-sign-non-image-artifact.md
> added quickstart for signing non-artifact

- content/en/docs/user-guides/how-to/directory-structure.md
> expand on the trust policy and trust store concepts

- content/en/docs/adopters.md
> venafi as adopter

- content/en/docs/user-guides/troubleshooting.md
fixes #223
Added a space to path in title to fix overrun issue. 
This provides an alternate solution to #255
> added space to header to fix overrun issue

- content/en/docs/user-guides/installation/cli.md
- layouts/partials/banner.html
> updated the installation guide and banner to v1.1.0

- content/en/docs/adopters.md
As suggested by @FeynmanZhou I extend the adopters page with the Nomad Admission Control Proxy
> Mention Nomad Admission Control Proxy

- content/en/blog/2024/announcing-notation-v1-1.md
a new release blog post for Notation v1.1.0
> blog: add a new release blog for v1.1.0

- content/en/docs/user-guides/how-to/plugin-management.md
> updated the plugin installation guide to v1.1.0

- content/en/blog/2024/bitnami-using-notation.md
Bitnami container images using notation. Closes #394.
> Bitnami now uses Notation for signing and verifying blog post

- CODEOWNERS
- MAINTAINERS
Addresses https://github.com/notaryproject/.github/issues/66, https://github.com/notaryproject/.github/issues/67, https://github.com/notaryproject/.github/issues/68, and https://github.com/notaryproject/.github/issues/69
Also moved @zr-msft to "in memoriam" :(
> Org maintainers update

- MAINTAINERS
Update:
- Add new org maintainers
> chore: update org maintainers

- content/en/docs/adopters.md
> Add Bitnami containers and Helm charts to the adopters list

- content/en/docs/user-guides/installation/cli.md
- layouts/partials/banner.html
update notation version to v1.1.1
> docs: update notation version to v1.1.1

- content/en/docs/faq.md
- content/en/docs/quickstart-guides/quickstart-sign-image-artifact.md
- content/en/docs/registry-support.md
Updates:
- Create a new page for registry support to make it more visible
- Update the FAQ page to point to the new page for registry support
> docs: add a page for registry support

- config.yaml
- content/en/docs/user-guides/installation/cli.md
- layouts/index.redirects
- layouts/partials/navbar.html
Add version control to v1.2.0
Fixes: #370 #350
---------
> chore: Added version drop-down menu to v1.2.0 

- config.yaml
- content/en/docs/user-guides/installation/cli.md
- layouts/index.redirects
- layouts/partials/navbar.html
Added version drop-down menu to v1.1.0 
Fixes: #370 #350
---------
> chore: Added version drop-down menu to v1.1.0 

- content/en/docs/user-guides/installation/cli.md
- layouts/partials/banner.html
Update:
- Update to latest version `v1.2.0`
> chore: update to latest version

- content/en/docs/user-guides/how-to/directory-structure.md
> docs(directory): add disclaimer on default unix directory

- content/en/docs/user-guides/how-to/directory-structure.md
> doc: add cache directory for CRL

- content/en/docs/user-guides/how-to/plugin-management.md
> doc: update venafi plugin version

- content/en/docs/user-guides/installation/cli.md
- layouts/partials/banner.html
update banner and installation page to v1.3.0
> doc: update banner and installation page to v1.3.0

- content/en/docs/adopters.md
Add Alibaba Cloud into [adopters](https://github.com/notaryproject/notaryproject.dev/blob/main/content/en/docs/adopters.md)
> doc: add alibaba cloud into adopters

- config.yaml
- content/en/docs/user-guides/installation/cli.md
update docs to v2.0-alpha.1 and add drop-down menu
Preview: https://deploy-preview-436--notarydev.netlify.app/docs/user-guides/installation/cli/
> docs: update docs to v2.0-alpha.1 and add drop-down menu
