notaryproject/notaryproject.dev

README.md

- Add missing markdown link definitions
- Drop mention of `make docker-serve`, which doesn't exist

README: add link definitions and other fixes

---

layouts/_default/_markup/render-link.html

- Closes #38
- No other changes to generated site files (modulo whitespace).

Render-link: trim whitespace from end template

---

content/en/community/meeting-notes/_index.md
content/en/community/meeting-notes/meeting-notes-2019.md
content/en/community/meeting-notes/meeting-notes-2020.md

Adding Notary V2 community meeting notes archive to website.
closes #58 
Deploy previews:
* https://deploy-preview-59--notarydev.netlify.app/community/meeting-notes/
* https://deploy-preview-59--notarydev.netlify.app/community/meeting-notes/meeting-notes-2019/
* https://deploy-preview-59--notarydev.netlify.app/community/meeting-notes/meeting-notes-2020/

adding Notary v2 community notes archive

---

config.yaml
content/en/_index.html

Since we don't need versioning yet, this PR removes the space that the versioning menu item takes up on the right side of the top menu bar by commenting out the versioning info in the config file.
This PR also removes some unused code in the main index file.
Deploy preview: https://deploy-preview-60--notarydev.netlify.app/

removing space from right side of top menu bar by removing versioning

---

README.md

The repo must be cloned because we're using submodules.

Update build setup instructions: the repo must be cloned

---

.gitpod.yml
README.md

I've been working with [gitpod.io](https://gitpod.io) cloud development environments, and have found it very useful, so I thought I'd make it a more official part of this repo.
* Updating README file to include information about available cloud IDE options for development.
Deploy preview: https://github.com/notaryproject/notaryproject.dev/blob/nw-2021-11-10-cloud-ide-description/README.md

Updating README with cloud IDE info

---

layouts/partials/footer.html

Looks like the oldest content on the site is from 2019. Please comment if this is an incorrect date.
Contributes to #16

Updating copyright range in footer

---

config.yaml

The original problem was part of the original site from which this was cloned. For details, see https://github.com/etcd-io/website/issues/437.
The only changes to the generated site files are:
```console
(cd public && git diff)
diff --git a/index.html b/index.html
```
```diff
index 2858667..99d390c 100644
--- a/index.html
+++ b/index.html
@@ -3,7 +3,7 @@
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
-<meta name="generator" content="Hugo 0.83.1" /><link rel="alternate" type="text/netlify" href="https://notaryproject.dev/_redirects">
+<meta name="generator" content="Hugo 0.83.1" /><link rel="alternate" type="application/rss&#43;xml" href="https://notaryproject.dev/index.xml">
<META NAME="ROBOTS" CONTENT="NOINDEX, …
```

Homepage fix: make rel="alternate" link to RSS

---

config.yaml

contributes to https://github.com/notaryproject/notaryproject.dev/issues/74
Adding new GA4 measurement ID for Google Analytics.

adding new GA4 measurement ID to config.yaml

---

content/en/docs/quickstart.md

Update quick start document for verifying using trust store and trust policy

doc: update quick start for verifying using ts/tp

---

content/en/blog/2022/oras-oci-artifacts-notation-signatures.md

This PR introduces a blog post about how Notation signatures are implemented through the ORAS library and stick to ORAS API specification for artifacts.
It also introduces the work to unify the specs into the OCI for managing artifacts. It finally highlights the next steps in the ecosystem that are planned.
Signed-off-by: Massimiliano Giovagnoli <me@maxgio.it>

Add a new blog post about Notation signatures and artifact specs

---

content/en/docs/quickstart.md

- Update distribution version for OCI artifact support
- Update directory path for different OS
- Add notes for tag2digest, and use digest instead of tag to identify container image
- Add a note for signature format using OCI Artifact manifest.

doc: update quick start for rc.1 release

---

config.yaml

- Followup to #74
- Effectively reverts #86
/cc @nate-double-u

Revert #86: drop GA4 ID from config

---

content/en/blog/2023/announcing-notation-rc2.md

Add RC.2 announcement blog based on the Release Notes at https://github.com/notaryproject/roadmap/pull/87.
See the [preview](https://deploy-preview-141--notarydev.netlify.app/blog/2023/announcing-notation-rc2/) page.

doc: add rc.2 announcement blog

---

content/en/blog/2023/notary-completes-fuzzing-security-audit.md

Add notary fuzzing security audit blog. It will be cross-post on the CNCF blog.

doc: add notary fuzzing security audit blog

---

content/en/docs/installation/cli.md

Fixed install doc that had typos when moving from RC2 to RC3
Fixes #159

fixed typo in install doc around rc2/rc3

---

content/en/docs/cli-reference/_index.md
content/en/docs/cli-reference/notation.md
content/en/docs/cli-reference/notation_certificate.md
content/en/docs/cli-reference/notation_certificate_add.md
content/en/docs/cli-reference/notation_certificate_delete.md
content/en/docs/cli-reference/notation_certificate_generate-test.md
content/en/docs/cli-reference/notation_certificate_list.md
content/en/docs/cli-reference/notation_certificate_show.md
content/en/docs/cli-reference/notation_inspect.md
content/en/docs/cli-reference/notation_key.md
content/en/docs/cli-reference/notation_key_add.md
content/en/docs/cli-reference/notation_key_delete.md
content/en/docs/cli-reference/notation_key_list.md
content/en/docs/cli-reference/notation_key_update.md
content/en/docs/cli-reference/notation_list.md
content/en/docs/cli-reference/notation_login.md
content/en/docs/cli-reference/notation_logout.md
content/en/docs/cli-reference/notation_plugin.md
content/en/docs/cli-reference/notation_plugin_list.md
content/en/docs/cli-reference/notation_policy.md
content/en/docs/cli-reference/notation_policy_import.md
content/en/docs/cli-reference/notation_policy_show.md
content/en/docs/cli-reference/notation_sign.md
content/en/docs/cli-reference/notation_verify.md
content/en/docs/cli-reference/notation_version.md

added notation CLI reference docs based on RC4

---

content/en/docs/quickstart.md

I noticed when smoke-test the current quickstart that i wasn't seeing the digest value being output from the `docker push`. I updated the section of the quickstart showing the digest value to use `docker inspect` instead of relying on the output of `docker push`.

added docker command to obtain digest instead of relying on output

---

content/en/docs/installation/cli.md

Added param to front matter to define the CLI release version and made use of [hugo shortcodes](https://gohugo.io/content-management/shortcodes/#param) to access that custom param for every instance where CLI release version is needed. 
In the future, new CLI release versions will only need a one-line update in the CLI install doc.

add page param and shortcode for cli release version

---

config.yaml
content/en/docs/cli-reference/notation.md
content/en/docs/cli-reference/notation_certificate.md
content/en/docs/cli-reference/notation_certificate_add.md
content/en/docs/cli-reference/notation_certificate_delete.md
content/en/docs/cli-reference/notation_certificate_generate-test.md
content/en/docs/cli-reference/notation_certificate_list.md
content/en/docs/cli-reference/notation_certificate_show.md
content/en/docs/cli-reference/notation_inspect.md
content/en/docs/cli-reference/notation_key.md
content/en/docs/cli-reference/notation_key_add.md
content/en/docs/cli-reference/notation_key_delete.md
content/en/docs/cli-reference/notation_key_list.md
content/en/docs/cli-reference/notation_key_update.md
content/en/docs/cli-reference/notation_list.md
content/en/docs/cli-reference/notation_login.md
content/en/docs/cli-reference/notation_logout.md
content/en/docs/cli-reference/notation_plugin.md
content/en/docs/cli-reference/notation_plugin_list.md
content/en/docs/cli-reference/notation_policy.md
content/en/docs/cli-reference/notation_policy_import.md
content/en/docs/cli-reference/notation_policy_show.md
content/en/docs/cli-reference/notation_sign.md
content/en/docs/cli-reference/notation_verify.md
content/en/docs/cli-reference/notation_version.md
content/en/docs/concepts/directory-structure.md
content/en/docs/how-to/oci-image-layout.md
static/css/prism.css

**Description**
This PR addresses issue [#193 ](https://github.com/notaryproject/notaryproject.dev/issues/193) by adding a floating copy button for command lines in order to improve user experience and make it easier to copy long command lines.

Added float copy button for the command lines #193

---

content/en/docs/quickstart.md

Fixes #231 
spelling mistake in quickstart.md
Improved sentence is `which registries are compatible with Notary`
The change from "registries" to "which registries" improves the clarity and readability of the sentence. It specifies that the reader should refer to the list of registries that are compatible with Notary.

Grammartical mistake

---

content/en/_index.html
content/en/docs/quickstart.md

1. 7cff57998a952b0fa3b2d49d951a78b54f065c46 replaces GitHub button with link to notation scenario and adds SVG icon indicating external link and opens that link in new tab a4687f94c23bedd00927fa64b065a5d3744e394d.
2. ded32bf6820170b7d908e893707914ea4d7627c5 adds info about online tutorial on `/docs/quickstart`
---
- https://deploy-preview-273--notarydev.netlify.app/
- https://deploy-preview-273--notarydev.netlify.app/docs/quickstart/
Closes #272

Add Notation interactive tutorial to website

---

content/en/docs/concepts/secure-plugin-development.md

added plugin development security doc

---

content/en/docs/troubleshooting.md

Fixing #260 
This PR includes modifications and updates to the following sections in the troubleshooting docs:
1. Updated: [How do I troubleshoot issues with signatures?](https://notaryproject.dev/docs/troubleshooting/#how-do-i-troubleshoot-issues-with-signatures)
2. [Modified: "Enabling notation CLI commands logging"](https://notaryproject.dev/docs/troubleshooting/#enabling-notation-cli-commands-logging)
3. [fixed missing closing parenthesis in this section](https://notaryproject.dev/docs/troubleshooting/#when-i-verify-an-artifact-i-get-the-error-error-open-homeconfignotationtrustpolicyjson-no-such-file-or-directory)
4. Included other types of trust stores in this[ section ](https://notaryproject.dev/docs/troubleshooting/#when-i-verify-an-artifact-i-get-the-error-homeconfignotationtrustst …

Updated troubleshooting docs

---

content/en/docs/how-to/plugin-management.md

add guide for managing plugins

---

content/en/docs/concepts/secure-deployment.md
content/en/docs/concepts/specs-requirements.md

added secure deployment guide

---

content/en/blog/2023/notation-completes-security-audit.md

Fix #298. This PR can be merged after https://github.com/notaryproject/notaryproject.dev/pull/302/ and https://github.com/notaryproject/notaryproject/pull/268 are merged into main.
Preview it at https://deploy-preview-303--notarydev.netlify.app/blog/2023/notation-completes-security-audit/

Create the blog post for the security audit result 2023

---

content/en/docs/troubleshooting.md

This PR fixed #291
It includes the following changes: 
1. I have included the use of  `-v` flag in the `notation verify` command to enable verbose logging in [when-i-verify-an-artifact-i-get-the-error-signature-is-not-produced-by-a-trusted-signer](https://notaryproject.dev/docs/troubleshooting/#when-i-verify-an-artifact-i-get-the-error-signature-is-not-produced-by-a-trusted-signer) 
2. The `notation cert show` output has been updated to display SHA256  thumbprints now. [when-i-verify-an-artifact-i-get-the-error-signature-is-not-produced-by-a-trusted-signer](https://notaryproject.dev/docs/troubleshooting/#when-i-verify-an-artifact-i-get-the-error-signature-is-not-produced-by-a-trusted-signer). 
3. Modified this section to include using `notation policy show` and/or `notation policy import …

updated troubleshooting docs to fix #291

---

content/en/docs/tutorials/trust-policy.md

Removes duplicated word `notation`

doc: remove typos in trust-policy.md

---

content/en/docs/troubleshooting.md

fixes #275 
workaround for 
- https://github.com/notaryproject/notation/issues/699
- https://github.com/notaryproject/notation/issues/700
- https://github.com/notaryproject/notation/issues/701

added troubleshooting to fix #275

---

config.yaml

I found another place on the Notary Project website that still displays the old naming and description. This is visible to the website users. So this PR updates the website title, description, and menu to align with the new brand.

chore: update website title, description, and menu to align with the new brand

---

content/en/docs/faq.md
content/en/docs/user-guides/how-to/_index.md
content/en/docs/user-guides/tutorials/_index.md
content/en/docs/user-guides/tutorials/trust-policy.md

fixes #325 by updating references to The Notary Project

---

content/en/docs/faq.md

minor tweak: the zot registry url redirects to v1.4.3 right now, but as releases continue, this will become stale. Leaving it bare will send folks to the latest version of the docs.

faq.md: no need to pin version of zot registry docs

---

config.yaml
content/en/blog/_index.md

The "Blog" link on Navbar was not getting the active class due to a misconfiguration in "config.yaml".
This PR fixes that.
Before:
Now:

Navbar: Fix active class not applied on Blog

---

netlify.toml

Fix https://github.com/notaryproject/notation/issues/783
How to test:
Access https://deploy-preview-375--notarydev.netlify.app/docs/how-to/registry-authentication/, it will redirect to https://deploy-preview-375--notarydev.netlify.app/docs/user-guides/how-to/registry-authentication/
After merging this PR, it should work and redirect the broken link https://notaryproject.dev/docs/how-to/registry-authentication/ to https://notaryproject.dev/docs/user-guides/how-to/registry-authentication/

chore: add redirect rule to resolve a broken link used by Notation CLI

---

config.yaml
content/en/docs/user-guides/installation/cli.md
layouts/index.redirects
layouts/partials/navbar.html

Added version control for documentation. Currently, the name of the current version in the drop-down is set as `Master (v0.1)`, and the version menu is named `version_menu: "v0.1"`. Ensure to edit the names accordingly when updating to a new version.
Fixes: #370 #350

Added Version control for documentation

---

config.yaml
content/en/blog/2024/announcing-notation-v1-2.md
content/en/docs/user-guides/how-to/timestamping.md
content/en/docs/user-guides/how-to/verify.md
content/en/docs/user-guides/installation/cli.md
layouts/index.redirects
layouts/partials/banner.html
layouts/partials/navbar.html

chore: sync main branch to v1.2.0

chore: sync main branch to v1.2.0

---

content/en/docs/user-guides/installation/cli.md
layouts/partials/banner.html

Update Notation CLI version to v1.1.2 due to v1.1.2 has been released https://github.com/notaryproject/notation/releases/tag/v1.1.2

chore: update Notation CLI version to v1.1.2

---

layouts/partials/footer.html

Scarf and the Notary Project have been in direct discussions, and Notary project maintainers have requested that a Scarf tracking pixel is added to the Notary documentation. This tracking pixel is fully GDPR-compliant, cookieless, and does not contain JavaScript. Further documentation surrounding this pixel can be found here: https://docs.scarf.sh/web-traffic/. 
@FeynmanZhou

Add Scarf documentation pixel to footer

---

content/en/docs/user-guides/tutorials/cicd.md

This PR adds CI/CD and GitOps solutions for notation. It helps users to easily find related doc links and references.
Preview: https://deploy-preview-419--notarydev.netlify.app/docs/user-guides/tutorials/cicd/

doc: add cicd and gitops solutions

---

layouts/partials/footer.html

Scarf and the Notary Project have been in direct discussions, and Notary project maintainers have requested that a Scarf tracking pixel is added to the Notary documentation v1-0. This tracking pixel is fully GDPR-compliant, cookieless, and does not contain JavaScript. Further documentation surrounding this pixel can be found here: https://docs.scarf.sh/web-traffic/.
@FeynmanZhou

Add Scarf documentation pixel to footer v1-0

---

layouts/partials/footer.html

Scarf and the Notary Project have been in direct discussions, and Notary project maintainers have requested that a Scarf tracking pixel is added to the Notary documentation v1-1. This tracking pixel is fully GDPR-compliant, cookieless, and does not contain JavaScript. Further documentation surrounding this pixel can be found here: https://docs.scarf.sh/web-traffic/.
@FeynmanZhou

Add Scarf documentation pixel to footer v1-1

---

layouts/partials/footer.html

Scarf and the Notary Project have been in direct discussions, and Notary project maintainers have requested that a Scarf tracking pixel is added to the Notary documentation v1-2. This tracking pixel is fully GDPR-compliant, cookieless, and does not contain JavaScript. Further documentation surrounding this pixel can be found here: https://docs.scarf.sh/web-traffic/.
@FeynmanZhou

Add Scarf documentation pixel to footer v1-2

---

config.yaml
content/en/docs/user-guides/how-to/plugin-management.md
content/en/docs/user-guides/installation/cli.md
layouts/partials/banner.html

This PR updates the installation guide to v1.3.1 and remove version info from plugin page. It's had to maintain version info for each plugin on notary project website so we should use an variable.

docs: update installation guide to v1.3.1 and remove version info from plugin page
